FROM node:14-alpine
RUN apk update && apk add --no-cache make gcc g++ python bash git findutils
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json

COPY tsconfig.json tsconfig.json
COPY .eslintrc.js .eslintrc.js
COPY src src
COPY test test
COPY versions.json versions.json
COPY .env .env
CMD npm run test-ci
